### ISSUE TITLE
can you offer the resfile.txt?

### ISSUE THREAD

**Issue by InvincibleZZH** [ekunger/iSeroSnFR#1]

**Comment by ekunger** [comment]
[resfile.txt](https://github.com/ekunger/iSeroSnFR/files/10943833/resfile.txt)

This file constrains aromatic residues to other aromatic residues. (WYTH). 
It may not be the exact one used for what was published in the paper, but it would be very similar. I hope this helps.

**Comment by InvincibleZZH** [comment]
thank you very much！
